### ISSUE TITLE
关于强制黑暗模式

### ISSUE THREAD

**Issue by et4cow** [Xposed-Modules-Repo/me.zhenxin.thisreallylite#4]
不想要强制黑暗模式，请问后续可以提供一个开关选择吗？感谢开发者大大～

**Comment by wangyuan0217** [comment]
这周吧

**Comment by wangyuan0217** [comment]
> 不想要强制黑暗模式，请问后续可以提供一个开关选择吗？感谢开发者大大～

已转移到 https://github.com/wangyuan0217/MyXposed 后面继续维护
